### ISSUE TITLE
Crontab

### ISSUE THREAD

**Issue by abszolut** [Thornsnake/MCRBot#10]
I don't understand your crontab settings:

TRAILING_STOP: "30 * * * * *",
        INVESTING: "0 3 0 * * *",
        REBALANCE: "0 */5 * * * *"

Trailing stop starts with 30 means every 30 minutes?
Investing and rebalance starts with 0. Why?

**Comment by Csubi76** [comment]
> 

https://crontab.guru/

**Comment by Thornsnake** [comment]
![Screenshot_20211223-100731_Chrome](https://user-images.githubusercontent.com/43046258/147216651-d1079d4b-13bb-43cc-b37e-99c5e68064c8.jpg)
Please read the comments.

**Comment by abszolut** [comment]
so first character is for the second. I see
