### ISSUE TITLE
No rebalancing after resuming trading

### ISSUE THREAD

**Issue by Mothluin** [Thornsnake/MCRBot#18]
Hi!
Tonight my bot instance started trading again after 72 hours freeze (trailing stop was triggered on 28/03).
This morning I looked into the logs and saw something weird was happening, as no rebalancing is performed for SOL, LINK and LUNA (out.log attached).

Is that because the amount to be traded is below the minimum accepted?
In such case, would it be better to start off any new investment cycle with a bigger amount on day 1?

Thanks

[mothluin-out.log](https://github.com/Thornsnake/MCRBot/files/8396965/mothluin-out.log)

**Comment by Mothluin** [comment]
Oh, yes.
I even restarted the bot at 08:52 thinking this would help...

**Comment by Thornsnake** [comment]
Yes, that is exactly what it is. The bot does acknowledge that it should rebalance (and writes that in the log), but then can't actually execute that rebalance because the low quantity would be rejected by the exchange. That issue usually resolves itself after a few investment cycles, when the invested balance is high enough.

**Comment by Mothluin** [comment]
Thanks for the confirmation! :)
I feel there's still something off with LUNA though:

```
2022-04-02T07:50:04: [CHECK] LUNA deviates -1.1387456287197462 USDT (-34.63%) -> [UNDERPERFORMING]
2022-04-02T07:50:04: [CHECK] Rebalance not necessary
2022-04-02T07:55:04: [CHECK] LUNA deviates -1.1383793712641643 USDT (-34.62%) -> [UNDERPERFORMING]
2022-04-02T07:55:04: [CHECK] Rebalance not necessary
2022-04-02T08:00:02: [CHECK] LUNA deviates -1.1310875727753649 USDT (-34.39%) -> [UNDERPERFORMING]
2022-04-02T08:00:02: [CHECK] Rebalance not necessary
2022-04-02T08:05:02: [CHECK] LUNA deviates -1.13275545489119 USDT (-34.48%) -> [UNDERPERFORMING]
2022-04-02T08:05:02: [CHECK] Rebalance not necessary
```

Before the bot resumed trading, I even converted the dust in CRO and withdrew it to make sure I'd start with a clean slate.
It's weird because the logs reads `UNDERPERFORMING` and `Rebalance not necessary` at the same time; plus, I don't really think LUNA is underperforming at this moment.

**Comment by Mothluin** [comment]
Never mind.
Regardless of the root cause, I fixed this myself the hard way 😉

Effectively, the fiat counter value of LUNA was lower than that of the other coins. Can't really understand why, but I'll live with that.

Thanks
