### ISSUE TITLE
Query on bots

### ISSUE THREAD

**Issue by kamigreed** [Thornsnake/MCRBot#3]
Hi, thanks a lot for the bot! Hoping for good results for the upcoming season. I have two questions though.

1) If I only want to pause investing, but DCA and rebalance can continue, do I just leave the bot as it is, or do I have to set investment to 0?

2) is there a quick way to sell everything off in the portfolio without triggering SL, or manually selling each asset?

Thank you.

**Comment by Thornsnake** [comment]
1. You just leave the bot as it is. If it runs out of money to invest, it will simply stop investing, and only rebalance from that point on.
2. I am still working on a GUI, so there's no button to press to make that process easy just yet. The quickest way would be to manually trigger the trailing stop. To do that, you can edit the "/data/PortfolioATH.json" file. Set the active state there to true, then set the all time high value to something ridiculous high. The bot will think it made a huge loss and sell.

**Comment by kamigreed** [comment]
Thanks!
