### ISSUE TITLE
Stop loss 

### ISSUE THREAD

**Issue by abszolut** [Thornsnake/MCRBot#8]
Is there a way to set up a Stop loss not just Trailing stop?

Thank you

**Comment by Mothluin** [comment]
I asked for the same feature in #5 but eventually understood that might be in contrast with the DCA idea.

I still think this would be a valuable addition whenever the following conditions are verified:
- You run out of quote currency (--> daily DCA suspended), and...
- The trailing stop is not engaged (meaning your portfolio worth never increased beyond `MIN_PROFIT`)

Under these conditions, should the market crash, you'd be defenseless and wouldn't even take advantage of it (no DCA).

This kind of situation happened me a couple times already.

**Comment by Thornsnake** [comment]
If you run out of quote currency, you optimally add more quote currency to continue to DCA. A stop loss really makes not much sense here, as the lower the price gets, the more you want to DCA and not sell for a loss.

If the bot was already below the stop loss limit, it would sell the moment you ran out of money to DCA, even if prices were already recovering. Only to then start to DCA again.
