### ISSUE TITLE
Trailing stop activated

### ISSUE THREAD

**Issue by abszolut** [Thornsnake/MCRBot#9]
Trailing stop activated variable will be false after restart or auto update?

Thank you

**Comment by Mothluin** [comment]
This was already answered in #4 .
There was no mention on what happens after an update, but I would assume the `PortfolioATH.json` would not be edited --> trailing stop status would match its pre-update status.

**Comment by Thornsnake** [comment]
A restart or update will have no effect on the status of the trailing stop. It will be in whatever state it was before.
